README.md
I'm starting to take a look at spread, and had some trouble with the examples in the README. It looks like they don't quite match up with what spread is expecting. I think this should fix it up.
=> Fix example yaml in README.md

spread/project.go
Trivial fix for a panic() when `spread -l` is run inside the snapd source tree. The reason for the crash is that the unity test has `systems: [ubuntu-16.04-64-grub]` so it is not available on the qemu backend.
=> fix crash when we run spread -l on snapd

spread/client.go
This ensure the environment is consistent between the linode/qemu backend and the adhoc backend. Some applications behave differently when they find SUDO_USER (and friends) in the environment.
=> client.go: when using sudo, erase SUDO_{USER,UID,GID}

spread/runner.go
Quick drive-by branch that shows how many jobs are still pending so that the user has an idea how long he/she has to wait.
=> show how many jobs are left

spread/qemu.go
This makes a serial port available for each qemu machine via telnet. So if something hangs (e.g. during reboot) or network does not come up the user can telnet to the serial port of the qemu machine. I hope we can enable this by default to make emergencies like this easier to debug.
=> make telnet available as serial console

spread/project.go
The current code ignores subdirectories in the suites tests path
that do not contain "task.yaml" files. However if there are files
inside the dir spread errors with:
```
error: open ...tests/lib.sh/task.yaml: not a directory
```
The attached code files this and the file is simpliy ignored.
Happy to add a spread test to it if that is something that looks
worthwhile to you.
=> Skip file in the suites tests path

spread/client.go, tests/match/checks/main/task.yaml
We were missing quotes around a variable in MATCH, meaning you couldn't use `^` and `$` in a regexp wanting to match a multiline string.
=> properly quote a variable in MATCH

spread/client.go
/snap/bin would normally we added from the system the test is running
on but as we override PATH now we should better add it there as well.
=> With exporting PATH now we miss the preconfigured /snap/bin in it

spread/project.go
Sorry for this regression, variants use the `+` prefix and I did not catch this when doing the original patch. This diff fixes it and I ran the entire snapd suite without errors with this modification.
=> fix incorrect match against variants

README.md, cmd/spread/main.go, spread/runner.go
This commit introduces a new mechanism to reexecute jobs reusing the
context.
This commit includes 2 new options:
-retries <int>: defines the number of times to retry any task to be
executed
-stop-on-fail: indicates if the retries have to be stopped once the task
fails.
=> Supporting repeating of tasks via -repeat

spread/project.go
This will provide the right error messages, instead of showing invalid
project name.
=> Fix error handling for readProject. (LP #1636657)

spread/project.go
The unmarshaled suite can be nil in a following situation:
project: demo
path: /home/demo
suites:
tests/:
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
=> Don't crash if suite is empty

cmd/spread/main.go
This was accidentally removed on commit
407d634069fee885e71e9769e389e02cb061e020
=> Adding repeat option again

spread/client.go
Use "golang.org/x/net/context" instead of "context" so that we get
back go 1.6 compatibility. This should fix the issue that snapd
fails in the autopkgtest setup in ubuntu 16.04. There we try to
build spread from the branch and it fails because "context" is
only available in go1.7.
The other whitespace change happend automatically because `go fmt`
is part of my editor. But I can remove it if you prefer it in a separate PR/commit.
=> add go1.6 compatibility

spread.yaml, spread/client.go
The PR#53 broke the timeout handling in dialOnReboot(). The
current code has some problems, especially when the target
does not survive the reboot (e.g. no working network after
the reboot):
- it will try to ssh.Dial() the target and never timeouts
- it will try to get uptime and on error retry forever
- ssh.Dial() is really doing the 5s timeout, on my system its
more like 60s
- This means that the timeout, relog and retry channel all
can have data in which case golang picks a random channel.
- This means on timeout in the worst case there is only a 1/3
chance that the timeout channel is handled which may lead
to much longer kill-timeouts (because ssh.Dial() takes ~60sec
for me).
I would love to write a test for this, I think we need to mock
ssh.Dial() for this particular test and ideally …
=> client: fix dialOnReboot() if the remote does not reply

spread/client.go
With SIGPIPE and "echo | grep -q" there is a race condition. If
grep exists before echo is finished writing data then echo will
get a SIGPIPE and this makes MATCH fail (which is very obscure
to the user). To fix this this PR switch to the "<<<" HERE
string.
=> spread: simplify MATCH by using "<<<" (thanks to chipaca)

spread/client.go
We ran into a confusing error when using MATCH in one of our snapd
tests. It runs out the issue can be reproduced with:
```
MATCH () {
{
set +ux
} 2> /dev/null;
return 0
}
MATCH foo <<< foo
test 1 -eq 2
```
When this is used, the output is:
```
$ bash -eux reproducer.sh
+ MATCH foo
```
I.e. the test line is not displayed.
It turns out the reason is that the MATCH function uses "set +ux"
which turns off the traces globally. When MATCH is used in a
pipe (e.g. "echo foo | MATCH foo") then MATCH is run in a
subshell and the turning off is not criticial. However when
using with here strings for file redirects and no subshell
is used turning off trace globally is an issue. The fix is
simply to run MATCH always in a subshell.
=> spread: run MATCH in a subshell

spread/google.go, spread/linode.go, spread/project.go, spread/runner.go
This is to be able to set the preserve-size option for each storage independently.
Currently for snpad test suite we are using "storage: preserve-size" at backend level but it is forcing all the systems to preserve the storage size even when it is not needed, which could produce errors testing images with are 1 or 3 GB of storage such as some imported images from other projects. 
This is an example of the error that this is causing: https://paste.ubuntu.com/p/HJcSgvBp4b/
It is happening installing tests dependencies on ubuntu-16.04-32 on spread-images project.
=> Define storage at system level

tests/adhoc/task.yaml
This branch fixes the ad-hoc test which can fail on hand-crafted parsing of .spread-reuse.yaml.
The parsing was made to be more robust with Python.
This is a follow-up for #91 but I was unable to push it there.
=> tests: fix ad-hoc test

spread/qemu.go
The kvm binary is non-standard packaging tweak in available in the
Debian world. To work on Fedora and all the other systems as well, we
can just invoke qemu-system-x86_64 with the -enable-kvm switch.
Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>
=> qemu: invoke qemu in a portable way

README.md, spread/client.go, tests/nomatch/checks/main/task.yaml, tests/nomatch/spread.yaml, tests/nomatch/task.yaml
Using MATCH -v works fine for single-line input, but fails
to make an equivalent assertion on multi-line input.  Add
a new helper which will error if match is found.
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>
=> introduce NOMATCH assertion helper

spread/runner.go
The idea is to be able to follow the test execution in the servers by
reading the spread output.
Having the information of the server on each line is easy to have
statistics and more accurate information of the entire spread execution
=> Add server label to the spread output

spread/google.go, spread/project.go
This is a feature to enable the secure boot option in google instances.
It is needed for running some uc20 tests because the key sealing in the
encryption tests needs secure boot to be enabled
The configuration in the spread.yaml should be:
systems:
- ubuntu-20.04-64:
workers: 6
secureboot: true
=> Adding option for systems created on google to start with secure boot enabled

.travis.yml, spread.yaml
There are two main reasons:
Go 1.10 fails to `go get` dependencies of spread as they have introduced build
flags unrecognized by 1.10, which causes spurious duplicate symbol errors. An
example can be seen on the test logs from
https://github.com/snapcore/spread/pull/111
The command "eval go get -v -t ./... " failed.
../../../golang.org/x/term/term_unix_linux.go:9:26: ioctlReadTermios redeclared in this block
previous declaration at ../../../golang.org/x/term/term_unix_aix.go:9:26
../../../golang.org/x/term/term_unix_linux.go:10:27: ioctlWriteTermios redeclared in this block
previous declaration at ../../../golang.org/x/term/term_unix_aix.go:10:2
This makes CI broken, this was not noticed simply because of low rate of
activity on the project.
The second reason is to get improved `go vet`, …
=> Bump base version of go to 1.13

spread/client.go
This simplification was suggested by go vet.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>
=> client: simplify append loop in Client.Send

spread/project.go, spread/project_test.go
The second argument to strconv.FormatInt is not integer size, but
numeric base. This is reported by go vet, as base cannot be larger than
36.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>
=> Fix OptionalInt.String use of strconv.FormatInt

spread/google.go, spread/humbox.go
This is flagged by `go vet` and is in accordance with go error naming conventions.
=> google,humbox: rename foo to errFoo

spread/google.go
Trivial fix after https://github.com/snapcore/spread/pull/124
=> spread: fix overlooked googleNotFound->errGoogleNotFound rename

.github/workflows/test.yaml
The idea is to use the published spread to trigger the tests execution.
We don't need to build spread in the github action machine because then
spread is built and tested in the target system.
Also it is included a step to discard workers in case it is needed.
=> Fix actions workflow and discard workers

spread/qemu.go
Fix BIOS path check, which called os.Stat() with incorrect path and thus never
used the bios file under ~/.spread/qemu/bios.
=> spread: fix bios path check, be more verbose about choosing the file

spread/client.go, spread/client_test.go, spread/export_test.go
This commit changes the code that detects if a reboot has happend based on the kernel `boot_id`. This is based on the idea from Valentin in PR#143 but slightly simplified as it will not parse the uuid but just tread as an opaque string.
=> client: use kernel `boot_id` to detect if a system got rebooted

README.md
It adds a simple command to install `spread` using Go tools.
It will help newcomers in installing the tool without having to look for other resources
=> chore: add super simple install instructions

spread/client.go
When spread connects to a machine as a non-root user, then it injects calls to
sudo -i to run commands as root. This effectively makes the artifact sending
logic equivalent to this script:
```sh
cd directory
sudo -i tar ...
```
The problem is that sudo -i changes the current working directory back to
/root. Pass -C or --directory= to tar, so that all the files are referenced
relative to the task directory.
=> Fix fetching artifacts when sudo -i changes directory

spread/lxd.go
With the ubuntu-22.04 image, the network interface seems to be sometimes named "enp5s0" instead of "eth0". To be compatible with both old and new releases, consider any non-loopback interface viable for retrieving an IP address.
=> backends: LXD: don't hardcode eth0

spread/client_test.go, spread/export_test.go, spread/google.go, spread/google_test.go
The googleImagesCache is currently not marked `ready`. This means while it is correctly build it is not used in subsequent calls to projectImages(). This commit set the cache to ready after it got populated.
The first commit fixes the issue, the second adds the test that shows the behavior. Happy to talk about the test more, it makes google a bit easier to test but maybe you prefer a different approach :)
=> google: mark cache as ready after it got populated

spread.yaml, spread/lxd.go, tests/lxd/checks/main/task.yaml, tests/lxd/spread.yaml, tests/lxd/task.yaml
In recent images, livecd-rootfs may be disabling SSH password authentication by default, with the intention that cloud-init would enabled that by placing a higher priority file under /etc/sshd/sshd_config.d/. See https://git.launchpad.net/livecd-rootfs/commit/live-build/ubuntu-cpc/hooks.d/chroot/052-ssh_authentication.chroot?id=480d5b26ea97e0bfebac8aedfa1f2bf7286f027a for reference.
Do the same as cloud-init would a drop a higher priority config overriding relevant SSHD settings.
=> spread(lxd): work around SSH password authentication disabled by livecd-rootfs

spread/export_test.go, spread/lxd.go, spread/lxd_test.go
Due to prefix or regular expression matching, `lxd list` may list multiple instances. To account for that, instead of assuming it will always return a slice where the first item is the one we're interested in, iterate over the result and pick the one that matches the name exactly. Return an error If no such match exists.
According to lxd documentation, the argument to the list command can be:
* A prefix of the instance name
* A regular expression on the instance name
* A key/value pair referring to a configuration item
* A key/value pair with a shorthand key
* A regular expression matching a config item
=> lxd: select server based on name from result

cmd/humbox/main.go, cmd/humbox/manager.go, spread/google.go, spread/humbox.go, spread/linode.go, spread/lxd.go, spread/project.go, spread/project_test.go, spread/qemu_test.go, spread/reuse.go, spread/runner.go
Package io/ioutil was deprecated in go 1.16. The same functionality
is provided by packages io or os, so replace the calls accordingly.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
=> chore: don't import deprecated io/ioutil package

spread/client.go
Package golang.org/x/crypo/ssh/terminal moved to golang.org/x/term.
Using the previous package name is deprecated.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
=> chore: don't import deprecated crypto/ssh/terminal

README.md, spread/export_openstack_test.go, spread/openstack.go, spread/openstack_test.go, spread/project.go, spread/runner.go
Adjust the OpenStack name casing consistently across documentation
and code to match official spelling, but keep "openstack" in unexported
names (don't use mixed-case "openStack").
=> refactor: adjust openstack name case

spread/client.go, spread/runner.go
permit working with Ubuntu Core
fixes: #165
discussion in #213
=> fix: revert artifact tar filter back to gzip
